language: php

php:
    - 5.5

sudo: false

before_script:
    - composer self-update
    - composer install --dev --no-interaction --prefer-source

script:
    - ./bin/phpspec run -fpretty --verbose
    - mysql -e 'create database bigblue;'
    - phpunit -c app

#env:
#    - DB=mysql SYMFONY__DATABASE__DRIVER=pdo_mysql

after_failure:
    - "cat /home/travis/build/lordkote/bigblue/app/logs/test.log"

test:
  adapter: mysql2
  database: bigblue
  username: root
  encoding: utf8