imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true


monolog:
    handlers:
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"

#doctrine:
#    dbal:
#        default_connection: default
#        connections:
#            default:
#                driver:   pdo_sqlite
#                path:     %kernel.cache_dir%/test.db

liip_functional_test:
    cache_sqlite_db: false