imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            #path:  "%kernel.logs_dir%/%kernel.environment%.log"
            path: "php://stderr"
            level: debug
        console:
            type:  console

# in production use the environment variables
parameters:
    #SYMFONY__DATABASE__HOST
    database_host:     "%database.host%"
    database_port:     ~
    #SYMFONY__DATABASE__NAME
    database_name:     "%database.name%"
    #SYMFONY__DATABASE__USER
    database_user:     "%database.user%"
    #SYMFONY__DATABASE__PASSWORD
    database_password: "%database.password%"
    #SYMFONY__DATABASE__DRIVER
    database_driver:   "%database.driver%"