app:
    resource: @AppBundle/Controller/
    type:     annotation
    defaults: {_format: json}

# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

appbundle_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: AppBundle:Security:login }

appbundle_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: AppBundle:Security:loginCheck }

# hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect
#
# hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login