#AppBundle\Entity\User.yml
AppBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        username:
            expose: true
        email:
            expose: true
    virtual_properties:
        getRoles:
            serialized_name: roles