---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: auth.dev www.auth.dev 192.168.33.106 localhost bigblue
    localhost: 127.0.0.1
    timezone: UTC
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - apache
    - php5
    - mysql
    - composer
    - phpcommon
    - app
    - sqlite
